baseURL: "https://blog.superbil.org/"
title: "Superbil.nil"
publishDir: "docs"
theme: "beautifulhugo"
googleAnalytics: ""
languageCode: "zh-tw"

params:
  author: "Superbil"
  copyright: "![Creative Commons License](http://i.creativecommons.org/l/by-nc-sa/2.5/tw/88x31.png)"
  poweredby: true
  jquery: true
  slicknav: true
  isCJKLanguage: true
  # cacheBustCSS: true
  # cacheBustJS: true