baseURL: "https://blog.superbil.org/"
title: "Superbil.nil"
publishDir: "docs"
theme: "beautifulhugo"

params:
  author: "Superbil"
  isCJKLanguage: true
  languageCode: "zh-tw"           # Use for RSS
  copyright: "![Creative Commons License](http://i.creativecommons.org/l/by-nc-sa/2.5/tw/88x31.png)"
  poweredby: true
  jquery: true
  slicknav: true
  googleAnalytics: "UA-52601-22"
  # cacheBustCSS: true
  # cacheBustJS: true
