baseURL: "https://blog.superbil.org/"
title: "Superbil.nil"
theme: "zen"
publishDir: "docs"

googleAnalytics: ""
languageCode: "zh-tw"

params:
  copyright: "This site is licensed under a
      [Creative Commons Attribution-ShareAlike 4.0 International License]
      (https://creativecommons.org/licenses/by-sa/4.0/)."