baseURL = "https://blog.superbil.org/"
locale = "zh-tw"
title = "Superbil.nil"
publishDir = "docs"
theme = "beautifulhugo"
pygmentsuseclasses = true
PygmentsCodeFences = true

SectionPagesMenu = "main"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "tags"
    identifier = "tags"
    url = "/tags/"

[params]
  isCJKLanguage = true
  languageCode = "zh-tw"           # Use for RSS
  copyright = "![Creative Commons License](http://i.creativecommons.org/l/by-nc-sa/2.5/tw/88x31.png)"
  poweredby = true
  jquery = true
  slicknav = true
  Content = false
  comments = true
  useHLJS = true
  hideAuthor = true
  since = "2013"

[params.author]
  name = "Superbil"

[services.disqus]
  shortname = "superbil-nil"